# Generated by Django 4.2 on 2025-04-15 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='desc',
            field=models.TextField(blank=True),
        ),
    ]
